FROM python:3.14-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt
RUN pip3 install --no-cahce-dir -r requirements.txt

COPY . .
EXPOSE 8000
CMD ["python3", "app.python"]